# Generated by Django 4.1.1 on 2022-09-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='library',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=400)),
                ('username', models.CharField(max_length=400)),
                ('issuedate', models.DateField()),
            ],
        ),
    ]
